# Generated by Django 5.2.6 on 2025-11-30 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('company', '0003_companybranding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', 'employee__user__last_name'], 'verbose_name': 'Présence', 'verbose_name_plural': 'Présences'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Retard (minutes)'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Heures travaillées'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True, verbose_name='Arrivée'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Départ'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes / Justification'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Présent'), ('late', 'En retard'), ('absent', 'Absent'), ('excused', 'Excusé')], default='absent', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'horaire")),
                ('start_time', models.TimeField(default='09:00', verbose_name='Heure de début')),
                ('end_time', models.TimeField(default='17:00', verbose_name='Heure de fin')),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text="Retard toléré avant d'être marqué comme 'En retard'", verbose_name='Période de grâce (minutes)')),
                ('is_monday', models.BooleanField(default=True, verbose_name='Lundi')),
                ('is_tuesday', models.BooleanField(default=True, verbose_name='Mardi')),
                ('is_wednesday', models.BooleanField(default=True, verbose_name='Mercredi')),
                ('is_thursday', models.BooleanField(default=True, verbose_name='Jeudi')),
                ('is_friday', models.BooleanField(default=True, verbose_name='Vendredi')),
                ('is_saturday', models.BooleanField(default=False, verbose_name='Samedi')),
                ('is_sunday', models.BooleanField(default=False, verbose_name='Dimanche')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='company.company')),
            ],
            options={
                'verbose_name': 'Horaire de travail',
                'verbose_name_plural': 'Horaires de travail',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.workschedule'),
        ),
    ]
