# Generated by Django 5.2.6 on 2025-12-01 12:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_companybranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('billing_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=254)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_nif', models.CharField(blank=True, max_length=100, verbose_name='NIF')),
                ('pdf_file', models.FileField(blank=True, upload_to='invoices/%Y/%m/')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe (Mastercard/Visa)'), ('orange_money', 'Orange Money'), ('wave', 'Wave')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Activer/désactiver ce moyen de paiement')),
                ('api_key', models.CharField(blank=True, help_text='Clé API publique ou ID marchand', max_length=500)),
                ('api_secret', models.CharField(blank=True, help_text='Clé API secrète', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret pour valider les webhooks', max_length=500)),
                ('test_mode', models.BooleanField(default=True, help_text='Mode test (sandbox)')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Configuration additionnelle')),
                ('notification_email', models.EmailField(help_text='Email pour recevoir les notifications de paiement', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration de Paiement',
                'verbose_name_plural': 'Configurations de Paiement',
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='XOF', help_text='Code devise (XOF=FCFA, EUR, USD)', max_length=3)),
                ('period', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=20)),
                ('max_employees', models.IntegerField(blank=True, help_text="Nombre max d'employés (null = illimité)", null=True)),
                ('max_users', models.IntegerField(blank=True, help_text="Nombre max d'utilisateurs (null = illimité)", null=True)),
                ('features', models.JSONField(default=dict, help_text='Liste des fonctionnalités incluses')),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text="Badge 'Populaire'")),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Plan d'Abonnement",
                'verbose_name_plural': "Plans d'Abonnement",
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('trial_end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('trial', 'Essai gratuit'), ('active', 'Actif'), ('past_due', 'Paiement en retard'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='trial', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_method', models.CharField(blank=True, help_text='Méthode de paiement par défaut', max_length=50)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='company.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('payment_method', models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(help_text='ID de transaction externe', max_length=255, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='billing.invoice')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.subscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Pourcentage'), ('fixed', 'Montant fixe')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('max_uses', models.IntegerField(blank=True, help_text="Nombre max d'utilisations (null = illimité)", null=True)),
                ('times_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Laisser vide pour tous les plans', to='billing.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Code Promo',
                'verbose_name_plural': 'Codes Promo',
                'ordering': ['-created_at'],
            },
        ),
    ]
