# Generated by Django 5.2.6 on 2025-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Carte bancaire (Stripe)'), ('orange_money', 'Orange Money Mali'), ('moov_money', 'Moov Money Mali'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe (Mastercard/Visa)'), ('orange_money', 'Orange Money Mali'), ('moov_money', 'Moov Money Mali'), ('wave', 'Wave')], max_length=50, unique=True),
        ),
    ]
