# Generated by Django 5.2.6 on 2025-11-28 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_type', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('zip', 'ZIP'), ('json', 'JSON')], max_length=20, verbose_name="Type d'export")),
                ('module', models.CharField(choices=[('dashboard', 'Tableau de bord'), ('users', 'Utilisateurs'), ('employees', 'Employés'), ('attendance', 'Présence'), ('leaves', 'Congés'), ('payroll', 'Paie'), ('documents', 'Documents'), ('settings', 'Paramètres')], max_length=50, verbose_name='Module source')),
                ('document_name', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Paramètres')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/%d/', verbose_name='Fichier')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Tâche Celery')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to='company.company', verbose_name='Entreprise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'export",
                'verbose_name_plural': "Journaux d'export",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='core_export_company_3a75c6_idx'), models.Index(fields=['user', '-created_at'], name='core_export_user_id_01f4ad_idx'), models.Index(fields=['status'], name='core_export_status_bee6f0_idx'), models.Index(fields=['celery_task_id'], name='core_export_celery__d1e788_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document_type', models.CharField(max_length=50, verbose_name='Type de document')),
                ('template_file', models.FileField(upload_to='templates/exports/', verbose_name='Fichier template')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_templates', to='company.company', verbose_name='Entreprise (optionnel pour templates globaux)')),
            ],
            options={
                'verbose_name': "Template d'export",
                'verbose_name_plural': "Templates d'export",
                'ordering': ['-created_at'],
                'unique_together': {('company', 'document_type', 'version')},
            },
        ),
    ]
