# Generated by Django 5.2.6 on 2025-11-29 23:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_companybranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPDFSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#6366f1', help_text='Couleur primaire (hex)', max_length=7, verbose_name='Couleur primaire')),
                ('secondary_color', models.CharField(default='#22d3ee', help_text='Couleur secondaire (hex)', max_length=7, verbose_name='Couleur secondaire')),
                ('font_family', models.CharField(choices=[('Helvetica', 'Helvetica'), ('Times-Roman', 'Times New Roman'), ('Courier', 'Courier')], default='Helvetica', max_length=50, verbose_name='Police de caractères')),
                ('footer_text', models.TextField(blank=True, help_text='Texte du pied de page', null=True, verbose_name='Pied de page')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature numérique')),
                ('signature_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du signataire')),
                ('signature_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre du signataire')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_settings', to='company.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Configuration PDF',
                'verbose_name_plural': 'Configurations PDF',
            },
        ),
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.CharField(choices=[('payslip', 'Bulletin de paie'), ('work_certificate', 'Attestation de travail'), ('salary_certificate', 'Attestation de salaire'), ('cnss_certificate', 'Certificat CNSS'), ('work_contract', 'Contrat de travail'), ('termination_letter', 'Lettre de licenciement'), ('transfer_letter', 'Lettre de mutation'), ('daily_attendance', 'Rapport de présence quotidien'), ('monthly_attendance', 'Rapport de présence mensuel'), ('employee_file', 'Dossier employé'), ('payroll_journal', 'Journal de paie')], max_length=50, verbose_name='Type de document')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configuration JSON (marges, espacements, sections)', verbose_name='Configuration')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_templates', to='company.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Template PDF',
                'verbose_name_plural': 'Templates PDF',
                'unique_together': {('company', 'template_type', 'name')},
            },
        ),
    ]
