# Generated by Django 5.2.6 on 2025-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Propriétaire SaaS'), ('admin', 'Admin'), ('rh', 'RH'), ('manager', 'Manager'), ('employe', 'Employe')], default='employe', max_length=20),
        ),
    ]
