# Generated by Django 5.2.6 on 2025-12-02 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transform_superuser_to_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text="Bloque l'accès à tous les utilisateurs sauf le owner", verbose_name='Mode maintenance')),
                ('maintenance_message', models.TextField(default='Nous effectuons une maintenance. Nous serons de retour bientôt.', verbose_name='Message de maintenance')),
                ('platform_name', models.CharField(default='SHINOBI GRH', max_length=255, verbose_name='Nom de la plateforme')),
                ('platform_url', models.URLField(default='https://shinobi-rh.com', verbose_name='URL de la plateforme')),
                ('support_email', models.EmailField(default='support@shinobi-rh.com', max_length=254, verbose_name='Email de support')),
                ('allow_registration', models.BooleanField(default=True, verbose_name='Autoriser les inscriptions')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Plateforme',
                'verbose_name_plural': 'Configuration Plateforme',
            },
        ),
    ]
