# Generated by Django 5.2.8 on 2025-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
    ]
