# Generated by Django 5.2.6 on 2025-11-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Désactiver pour geler l'accès client"),
        ),
        migrations.AddField(
            model_name='company',
            name='max_users',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='company',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratuit'), ('startup', 'Startup'), ('enterprise', 'Entreprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
