# Generated by Django 5.2.6 on 2025-11-29 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_active_company_max_users_company_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_color', models.CharField(default='#4472C4', help_text='Couleur principale (format hex: #RRGGBB)', max_length=7)),
                ('secondary_color', models.CharField(default='#2e7d32', help_text='Couleur secondaire (format hex: #RRGGBB)', max_length=7)),
                ('accent_color', models.CharField(default='#ed6c02', help_text="Couleur d'accent (format hex: #RRGGBB)", max_length=7)),
                ('header_text', models.TextField(blank=True, help_text="Texte d'en-tête pour les documents")),
                ('footer_text', models.TextField(blank=True, help_text='Texte de pied de page pour les documents')),
                ('signature_name', models.CharField(blank=True, help_text='Nom du signataire (ex: Directeur RH)', max_length=255)),
                ('signature_title', models.CharField(blank=True, help_text='Titre du signataire', max_length=255)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
